### ISSUE TITLE
driver and profile 

### ISSUE THREAD

**Issue by eeriesoft** [fysh711426/UndetectedChromeDriver#17]
OpenQA.Selenium.WebDriverException
  HResult=0x80131500
  Message=unknown error: cannot determine loading status
from unknown error: unexpected command response
  (Session info: chrome=103.0.5060.114)
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.set_Url(String value)
   at OpenQA.Selenium.Navigator.GoToUrl(String url)
   at SeleniumUndetectedChromeDriver.UndetectedChromeDriver.GoToUrl(String url)
   at GMailPWC.Program.Main(String[] args) in C:\Users\mhgsa\source\repos\GMailPWC\Program.cs:line 59

https://prnt.sc/mKVSz9FiiO7F
https://prnt.sc/yXwDqzL_XWIQ
#######################################################################
AND SOME TIME SHOW 
Your preferences can not be read.
Some features may be unavailable and changes to preferences won't be saved.
https://prnt.sc/TjBmk9M50X48

**Comment by fysh711426** [comment]
It should be a chrome version problem.  

https://stackoverflow.com/questions/72758996/selenium-seleniumwire-unknown-error-cannot-determine-loading-status-from-unkn

**Comment by fysh711426** [comment]
> Your preferences can not be read.

This should be resolved by setting userDataDir.

**Comment by eeriesoft** [comment]
Thanks
