### ISSUE TITLE
'Unable to receive message from renderer' error after setting userDataDir

### ISSUE THREAD

**Issue by anastasiam** [fysh711426/UndetectedChromeDriver#85]
Hello!

When setting `userDataDir` and navigating to a url I get an error `Unable to receive message from renderer` in console output. When I try to do anything else, after this message appears, I get `OpenQA.Selenium.WebDriverException: disconnected: not connected to DevTools` exception.
If `userDataDir` is not being set it works perfectly fine.

Error in console:
![Screenshot 2024-08-14 174802](https://github.com/user-attachments/assets/b85180fb-9470-44f8-9827-fce08c2df61f)

Exception:
```
OpenQA.Selenium.WebDriverException: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=127.0.6533.101)
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.GetScreenshot()
```

My code:
```
        using var chromeDriver = UndetectedChromeDriver.Create(
            headless: true,
            driverExecutablePath: await new ChromeDriverInstaller().Auto(),
            userDataDir: $@"{Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)}\Google\Chrome\User Data"
        );

        Console.WriteLine("Navigating to nowsecure.nl...");
        chromeDriver.GoToUrl("https://nowsecure.nl");
        
        Console.WriteLine("Getting screenshot...");
        var screenshot = chromeDriver.GetScreenshot();
```

Even though I set `headless: true`, it behaves like it's set to `false`. The window is opening, navigating to the url and closing immediately.

I would appreciate any help.

**Comment by anastasiam** [comment]
> I am no expert, but I think this happens when you have an instance of chromedriver.exe running. You should run a taskkill chromedriver.exe prior to running each time. You most likely started it, then stopped, and didnt clean it up. You cannot have two instances in the same directory or you get this error.

When I execute `taskkill /f /im chromedriver.exe`, it shows `ERROR: The process "chromedriver.exe" not found`. I terminated all Google Chrome processes as well. I was even restarting my computer.

**Comment by STRATZ-Ken** [comment]
Did you try `chrome.exe` as well?

**Comment by anastasiam** [comment]
> Did you try `chrome.exe` as well?

Yes

**Comment by anastasiam** [comment]
I've also tried to copy User Data folder to a separate one and use it, but I still get the same error.
